### ISSUE TITLE
CPLEX Dependency

### ISSUE THREAD

**Issue by Rohak72** [PlanesLab/gMCSpy#1]
Hello,

Thanks for creating this tool, I imagine it'll be a useful asset to my metabolic modeling work. When trying to install, unfortunately, I run into an error with the cplex dependency. I currently use Gurobi as my solver of choice, so is there any way to circumvent this requirement and proceed with the package installation? Please let me know your thoughts, much appreciated!

Cheers,
Rohak

**Comment by cjrodriguez98** [comment]
Hello Rohak! 

Thank you for the feedback, could you send us what error araises when you try to install cplex?

best regards, 
Carlos

**Comment by cjrodriguez98** [comment]
Hey again! 

Thanks for the trace back. 

I have some questions to try to support you in the best possible way. 

What version of python are you using?

Thanks!

**Comment by cjrodriguez98** [comment]
Hello again Rohak!

I have been trying to replicate the error to find where the conflict is. From here I have not been able to replicate the issue. 

I would suggest creating a new conda enviroment with python 3.10,

conda create -nameOfEnviroment python=3.10

And then try to install gmcspy. 

Please contact me again if you have any issue. 

Carlos
